### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by daveroberts** [toranb/react-fireup-clone-jspm#1]
I know you probably have zero interest in maintaining this, but I tried to build both this and react-jspm-gulp-twitter-example per the instructions in the README, and ran into errors.

``` bash
jspm install react=github:reactjs/react-bower@0.10.0 -o "{main: 'react', format: 'global'}" -f
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/dave/react-fireup-clone-jspm/node_modules/jspm/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/jspm/jspm.js:33:5)
    at Liftoff.launch (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/jspm/node_modules/liftoff/index.js:163:8)
    at Object.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/jspm/jspm.js:29:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Is this a result of the toolset changing in the past seven months?

**Comment by toranb** [comment]
haha, it's actually not a lack of interest but rather a lack of experience with it. Back when I was learning React (mid 2014) the React Router was early days also. Combine that with a few revs of React itself and I'm far from an expert on this today. I _might_ need to see if I can get a version of this working without bower/etc so it can be a long(er) lasting reference app w/out dep management hell like is shown here
